# Permalinks
permalink:        pretty
#relative_permalinks: true

title: SNAGs CT
tagline: 'Our meeting place'
description: >- # this means to ignore newlines until "baseurl:"
  Stamford Norwalk Area Gamers. We are a group of board game enthusiasts that meet regularly to play and
  hangout.
url: "https://www.snagsct.tk"
baseurl: /
github_username: gandazgul

# Build settings
theme: minima
# Gems
plugins:
- jekyll-gist
- jekyll-paginate
- jekyll-seo-tag

exclude:
- .editorconfig
- .git
- .jekyll-cache
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md

sass:
  sass_dir: _sass
  style: :compressed

paginate: 5

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Carlos Ravelo
  url: https://github.com/gandazgul
  email: ravelo.carlos@gmail.com

# Custom vars
version: 2.1.0
