# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = "Business Frontpage - Start Bootstrap Template"
theme = "hugo-business-frontpage-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Carlos Ravelo"
    description = "The Stamford Norwalk Area Gamers website. Find upcoming and past events, news and other group information."

    [params.navbar]
        name = "SNAGs CT"
        url = "#"

        [[params.navbar.nav]]
        current = true
        name = "Home"
        url = "#"
        [[params.navbar.nav]]
        name = "About"
        url = "/about"
        [[params.navbar.nav]]
        name = "Events"
        url = "/events"
        [[params.navbar.nav]]
        name = "Contact"
        url = "/contact"

    [params.header]
        name = "Stamford Norwalk Area Gamers (SNAGsCT)"
        tagline = "The Stamford Norwalk Area Gamers website. Find upcoming and past events, news and other group information."

    [params.summary]
        url = "/events"

        [params.summary.description]
        [[params.summary.description.items]]
        description = "Find our upcoming and past events and access our shared calendar!"
        [[params.summary.description.items]]
        description = "For questions about a specific event, leave a comment on that event's page."

        [params.summary.contact]
        name = "SNAGsCT"
#        address1 = "3481 Melrose Place"
#        address2 = "Beverly Hills, CA 90210"
#        phone = "(123) 456-7890"
        email = "Do we want this?@example.com"

    [params.projects]

        [[params.projects.sections]]
        # title = "Section 1"

        [[params.projects.sections.rows]]
#         title = "Section 1, Row 1"

        [[params.projects.sections.rows.items]]
        title = "Card title 1"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "#"
        image = "image.jpeg"
        [[params.projects.sections.rows.items]]
        title = "Card title 2"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "Card title 3"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
        url = "#"
        # image = "image.png"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 2"

        [[params.projects.sections.rows.items]]
        title = "Card title 4"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "Card title 5"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        url = "#"
        # image = "image.png"


        [[params.projects.sections]]
        # title = "Section 2"

        [[params.projects.sections.rows]]
        # title = "Section 2, Row 1"

        [[params.projects.sections.rows.items]]
        title = "Card title 1"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "Card title 2"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        url = "#"
        # image = "image.png"
        [[params.projects.sections.rows.items]]
        title = "Card title 3"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
        url = "#"
        # image = "image.png"

        [[params.projects.sections.rows]]
        # title = "Section 2, Row 2"

        [[params.projects.sections.rows.items]]
        title = "Card title 4"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "#"
        # image = "image.png"

    [params.footer]
        copyright = "Copyright © SNAGsCT"
